// Purge: rebuildable project build artifacts under the user's project
// containers. Only whitelisted artifact names are ever candidates, discovery
// never descends into a found artifact, git state produces report-only
// blocker badges (never a "safe to delete" verdict), and ambiguous names
// ("bin", "target", ...) require a project marker file as evidence.

use crate::scanutil::{self, CancelFlag};
use mole_core::plan::{DeletionPlan, Scope};
use mole_core::state::load_purge_paths;
use serde::Serialize;
use std::path::{Path, PathBuf};
use std::sync::atomic::Ordering;

/// Canonical purge targets (port of MOLE_PURGE_TARGETS in purge_shared.sh).
pub const PURGE_TARGETS: &[&str] = &[
    "node_modules",
    "target",
    "build",
    "dist",
    "venv",
    ".venv",
    ".pytest_cache",
    ".mypy_cache",
    ".tox",
    ".nox",
    ".ruff_cache",
    ".gradle",
    ".terragrunt-cache",
    "__pycache__",
    ".next",
    ".nuxt",
    ".output",
    "vendor",
    "bin",
    "obj",
    ".turbo",
    ".parcel-cache",
    ".dart_tool",
    ".zig-cache",
    "zig-out",
    ".angular",
    ".svelte-kit",
    ".astro",
    "coverage",
    "DerivedData",
    "Pods",
    ".cxx",
    ".expo",
    ".build",
    // Extra rebuildable caches (all regenerated by the next build/install).
    ".cache",
    ".vite",
    ".pnpm-store",
    ".eggs",
    ".swiftpm",
    ".jest",
    ".eslintcache",
    ".nyc_output",
    "out",
    "tmp",
    ".tmp",
    "Carthage",
];

/// Files whose presence marks a directory as a project root. Discovery walks
/// containers until it finds one of these (or .git), so projects can live at
/// any depth (e.g. ~/source/project/<name>) instead of only container/<name>.
const PROJECT_MARKERS: &[&str] = &[
    ".git",
    "package.json",
    "Cargo.toml",
    "pyproject.toml",
    "setup.py",
    "requirements.txt",
    "go.mod",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "Gemfile",
    "composer.json",
    "Package.swift",
    "Podfile",
    "pubspec.yaml",
    "CMakeLists.txt",
    "Makefile",
    "mix.exs",
    "build.zig",
];

/// True when `dir` looks like a project root (has a marker or .sln/.csproj).
/// One read_dir instead of ~20 stat calls: discovery visits many dirs.
fn is_project(dir: &Path) -> bool {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return false;
    };
    entries.flatten().any(|e| {
        let name = e.file_name();
        let name = name.to_string_lossy();
        PROJECT_MARKERS.contains(&name.as_ref())
            || name.ends_with(".sln")
            || name.ends_with(".csproj")
    })
}

/// Default search paths when the user has no purge_paths config (port of
/// MOLE_PURGE_DEFAULT_SEARCH_PATHS, minus CLI-specific worktree containers).
fn default_search_paths(home: &str) -> Vec<PathBuf> {
    [
        "www",
        "dev",
        "Projects",
        "GitHub",
        "Code",
        "Workspace",
        "Repos",
        "Development",
        "source",
        "src",
        "work",
        "git",
        "repos",
        "workspace",
        "Documents/GitHub",
        "Desktop",
        "Library/CloudStorage",
    ]
    .iter()
    .map(|p| PathBuf::from(home).join(p))
    .collect()
}

/// Ambiguous artifact names and the project marker that authorizes them:
/// "bin"/"obj" need a .NET solution, "target" needs Cargo/Maven, "build"
/// and "dist" need a build-system file. No marker → not a candidate.
fn artifact_authorized(project: &Path, artifact_name: &str) -> bool {
    let has_any = |names: &[&str]| names.iter().any(|n| project.join(n).exists());
    let has_ext = |ext: &str| {
        std::fs::read_dir(project)
            .map(|entries| {
                entries
                    .flatten()
                    .any(|e| e.path().extension().is_some_and(|x| x == ext))
            })
            .unwrap_or(false)
    };
    match artifact_name {
        "bin" => has_ext("sln") || has_ext("csproj") || has_any(&["go.mod"]),
        "obj" => has_ext("sln") || has_ext("csproj"),
        "target" => has_any(&["Cargo.toml", "pom.xml"]),
        "build" | "dist" => has_any(&[
            "package.json",
            "build.gradle",
            "build.gradle.kts",
            "CMakeLists.txt",
            "setup.py",
            "pyproject.toml",
            "Makefile",
        ]),
        "vendor" => has_any(&["composer.json", "go.mod"]),
        // Generic names: only inside a recognised project, never bare folders.
        "out" | "tmp" | ".tmp" | ".cache" => is_project(project),
        _ => true,
    }
}

/// One project's discovered state for the preview.
#[derive(Debug, Serialize)]
pub struct ProjectReport {
    pub root: String,
    /// Report-only blocker badges: dirty / no-git. Never a safety verdict.
    pub blockers: Vec<String>,
    /// Days since the project was last worked on (git commit or dir mtime);
    /// None when neither could be read. The UI compares this against the
    /// user's configurable threshold to decide the default checkbox state.
    pub idle_days: Option<u64>,
}

/// `git status --porcelain` paths of modified tracked files, or None when
/// git could not answer (not a repo, or the probe failed). Untracked files
/// are skipped: irrelevant to artifact deletion, and listing them crawls
/// the whole tree on big repos.
fn git_modified_paths(project: &Path) -> Option<Vec<PathBuf>> {
    if !project.join(".git").exists() {
        return None;
    }
    let out = std::process::Command::new("git")
        .arg("-C")
        .arg(project)
        .args(["status", "--porcelain", "--untracked-files=no", "-z"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    // Porcelain v1 -z: "XY path\0" entries; renames add a second "\0orig".
    // We only need the paths, so every entry longer than 3 bytes is one.
    Some(
        out.stdout
            .split(|b| *b == 0)
            .filter(|e| e.len() > 3)
            .map(|e| project.join(String::from_utf8_lossy(&e[3..]).into_owned()))
            .collect(),
    )
}

/// Days since the last real activity. Git repo: newest of the last commit
/// and the mtimes of files with uncommitted changes. Otherwise: newest of
/// the marker files and the top-level regular files. The project dir's own
/// mtime and `.git`'s mtime are deliberately NOT used: both get refreshed
/// by noise (.DS_Store, lock files, our own `git status` writing
/// index.lock) and reported every project as "changed today".
fn idle_days(project: &Path, modified: Option<&[PathBuf]>) -> Option<u64> {
    let now = std::time::SystemTime::now();
    let mut latest: Option<std::time::SystemTime> = None;
    let mut bump = |t: std::time::SystemTime| {
        if latest.is_none_or(|l| t > l) {
            latest = Some(t);
        }
    };
    let mtime = |p: &Path| std::fs::symlink_metadata(p).and_then(|m| m.modified()).ok();
    match modified {
        Some(paths) => {
            let out = std::process::Command::new("git")
                .arg("-C")
                .arg(project)
                .args(["log", "-1", "--format=%ct"])
                .output();
            if let Ok(o) = out {
                if let Ok(secs) = String::from_utf8_lossy(&o.stdout).trim().parse::<u64>() {
                    bump(std::time::UNIX_EPOCH + std::time::Duration::from_secs(secs));
                }
            }
            // Uncommitted work counts too (bounded: a huge dirty tree is
            // "active" after the first few hundred files anyway).
            for p in paths.iter().take(500) {
                if let Some(t) = mtime(p) {
                    bump(t);
                }
            }
        }
        None => {
            for marker in PROJECT_MARKERS {
                if *marker == ".git" {
                    continue;
                }
                if let Some(t) = mtime(&project.join(marker)) {
                    bump(t);
                }
            }
            if let Ok(entries) = std::fs::read_dir(project) {
                for e in entries.flatten() {
                    let name = e.file_name();
                    if name.to_string_lossy().starts_with('.') {
                        continue;
                    }
                    if e.file_type().is_ok_and(|t| t.is_file()) {
                        if let Some(t) = mtime(&e.path()) {
                            bump(t);
                        }
                    }
                }
            }
        }
    }
    let latest = latest?;
    Some(now.duration_since(latest).unwrap_or_default().as_secs() / 86_400)
}

/// Purge plan plus per-project blocker badges.
#[derive(Debug, Serialize)]
pub struct PurgePlanOutput {
    pub plan: DeletionPlan,
    pub projects: Vec<ProjectReport>,
}

/// Git working-tree blockers, report-only (dirty means "look before you
/// leap", not "unsafe"; clean means nothing beyond that).
fn git_blockers(project: &Path, modified: Option<&[PathBuf]>) -> Vec<String> {
    let mut blockers = Vec::new();
    if !project.join(".git").exists() {
        return blockers;
    }
    match modified {
        Some(paths) if !paths.is_empty() => blockers.push("dirty".into()),
        Some(_) => {}
        // A git probe that cannot answer is reported, not assumed clean.
        None => blockers.push("git-unknown".into()),
    }
    blockers
}

/// Walk one project looking for purge targets (bounded depth, never descending
/// into a found artifact or into .git).
fn find_artifacts(project: &Path, depth: usize, out: &mut Vec<PathBuf>, cancel: &CancelFlag) {
    if depth > 4 || cancel.load(Ordering::Relaxed) {
        return;
    }
    let Ok(entries) = std::fs::read_dir(project) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Ok(meta) = std::fs::symlink_metadata(&path) else {
            continue;
        };
        if !meta.is_dir() || meta.file_type().is_symlink() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().into_owned();
        if name == ".git" {
            continue;
        }
        if PURGE_TARGETS.contains(&name.as_str()) {
            if artifact_authorized(project, &name) {
                out.push(path);
            }
            // Never descend into an artifact (its contents are one unit).
            continue;
        }
        // Hidden non-target dirs stay out of discovery (CLI parity).
        if name.starts_with('.') {
            continue;
        }
        find_artifacts(&path, depth + 1, out, cancel);
    }
}

/// Find project roots under a container: a dir with a project marker is a
/// root (not descended further — find_artifacts handles nested packages);
/// otherwise keep walking up to 3 levels. A container that is itself a
/// project (purge_paths pointing straight at a repo) counts too. Hidden dirs,
/// symlinks and purge targets themselves are never entered.
fn discover_projects(dir: &Path, depth: usize, out: &mut Vec<PathBuf>, cancel: &CancelFlag) {
    if cancel.load(Ordering::Relaxed) {
        return;
    }
    if is_project(dir) {
        out.push(dir.to_path_buf());
        return;
    }
    if depth >= 3 {
        return;
    }
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Ok(meta) = std::fs::symlink_metadata(&path) else {
            continue;
        };
        if !meta.is_dir() || meta.file_type().is_symlink() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') || PURGE_TARGETS.contains(&name.as_str()) {
            continue;
        }
        discover_projects(&path, depth + 1, out, cancel);
    }
}

/// Build the purge plan across the configured (or default) search paths.
/// Marker-based project discovery up to 3 levels below each container.
pub fn build_plan(
    home: &str,
    cancel: &CancelFlag,
    mut progress: impl FnMut(&str),
) -> PurgePlanOutput {
    let search = load_purge_paths(home)
        .map(|v| v.into_iter().map(PathBuf::from).collect::<Vec<_>>())
        .unwrap_or_else(|| default_search_paths(home));

    // Phase 1: discovery (cheap directory listing).
    let mut found: Vec<(PathBuf, Vec<PathBuf>)> = Vec::new();
    for container in search {
        if !container.is_dir() {
            continue;
        }
        let mut roots = Vec::new();
        discover_projects(&container, 0, &mut roots, cancel);
        for project in roots {
            if cancel.load(Ordering::Relaxed) {
                // Cancellation returns an EMPTY plan: a timed-out producer
                // must never feed partial output into a deletion flow.
                return PurgePlanOutput {
                    plan: DeletionPlan::default(),
                    projects: Vec::new(),
                };
            }
            progress(&project.to_string_lossy());
            let mut artifacts = Vec::new();
            find_artifacts(&project, 0, &mut artifacts, cancel);
            if !artifacts.is_empty() {
                found.push((project, artifacts));
            }
        }
    }

    // Phase 2: git probes (status + log per project) run a few at a
    // time instead of strictly one after another; they are IO-bound.
    let reports: Vec<Option<ProjectReport>> = {
        let queue = std::sync::Mutex::new(found.iter().enumerate().collect::<Vec<_>>());
        let results = std::sync::Mutex::new((0..found.len()).map(|_| None).collect::<Vec<_>>());
        std::thread::scope(|scope_| {
            for _ in 0..4.min(found.len().max(1)) {
                scope_.spawn(|| loop {
                    let job = queue.lock().unwrap().pop();
                    let Some((idx, (project, _))) = job else {
                        break;
                    };
                    if cancel.load(Ordering::Relaxed) {
                        break;
                    }
                    // One git status per project feeds both the blocker
                    // badge and the idle-days estimate.
                    let modified = git_modified_paths(project);
                    let report = ProjectReport {
                        root: project.to_string_lossy().into_owned(),
                        blockers: git_blockers(project, modified.as_deref()),
                        idle_days: idle_days(project, modified.as_deref()),
                    };
                    results.lock().unwrap()[idx] = Some(report);
                });
            }
        });
        results.into_inner().unwrap()
    };

    let mut plan = DeletionPlan::default();
    let mut projects = Vec::new();
    for ((_, artifacts), report) in found.into_iter().zip(reports) {
        let Some(report) = report else {
            // Probe skipped by cancellation → no partial output.
            return PurgePlanOutput {
                plan: DeletionPlan::default(),
                projects: Vec::new(),
            };
        };
        // One shared section so the UI shows a single "Projects" card;
        // per-project detail comes from `projects` (matched by path).
        let candidates = scanutil::parallel_candidates(&artifacts, "projects", Scope::User, cancel);
        if candidates.is_empty() {
            continue;
        }
        plan.candidates.extend(candidates);
        projects.push(report);
    }

    PurgePlanOutput { plan, projects }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::AtomicBool;
    use std::sync::Arc;

    #[test]
    fn ambiguous_targets_need_project_markers() {
        let tmp = tempfile::tempdir().unwrap();
        let rust_proj = tmp.path().join("Projects/rusty");
        std::fs::create_dir_all(rust_proj.join("target/debug")).unwrap();
        std::fs::write(rust_proj.join("Cargo.toml"), b"[package]").unwrap();
        let docs = tmp.path().join("Projects/docs");
        // "target" without Cargo.toml/pom.xml: user data, not an artifact.
        std::fs::create_dir_all(docs.join("target/archive")).unwrap();
        let js = tmp.path().join("Projects/webapp");
        std::fs::create_dir_all(js.join("node_modules/dep")).unwrap();
        std::fs::write(js.join("package.json"), b"{}").unwrap();
        // Nested layout (container/group/project) must be discovered too.
        let deep = tmp.path().join("Projects/group/deep");
        std::fs::create_dir_all(deep.join("node_modules/dep")).unwrap();
        std::fs::write(deep.join("package.json"), b"{}").unwrap();
        // Bare node_modules with no project marker is not a project.
        std::fs::create_dir_all(tmp.path().join("Projects/loose/node_modules/x")).unwrap();

        let config_dir = tmp
            .path()
            .join(".config")
            .join(mole_core::brand::CONFIG_DIR);
        std::fs::create_dir_all(&config_dir).unwrap();
        std::fs::write(
            config_dir.join("purge_paths"),
            format!("{}/Projects\n", tmp.path().display()),
        )
        .unwrap();

        let cancel: CancelFlag = Arc::new(AtomicBool::new(false));
        let out = build_plan(&tmp.path().to_string_lossy(), &cancel, |_| {});
        let paths: Vec<&str> = out
            .plan
            .candidates
            .iter()
            .map(|c| c.path.as_str())
            .collect();
        assert!(paths.iter().any(|p| p.ends_with("rusty/target")));
        assert!(paths.iter().any(|p| p.ends_with("webapp/node_modules")));
        assert!(paths.iter().any(|p| p.ends_with("group/deep/node_modules")));
        assert!(!paths.iter().any(|p| p.contains("loose/")));
        let webapp = out
            .projects
            .iter()
            .find(|p| p.root.ends_with("webapp"))
            .expect("webapp reported");
        // Just created → idle 0 days.
        assert_eq!(webapp.idle_days, Some(0));
        // A project whose files are old must NOT read as "today" just because
        // the directory itself was touched (node_modules created now).
        let old = tmp.path().join("Projects/old");
        std::fs::create_dir_all(old.join("node_modules/dep")).unwrap();
        std::fs::write(old.join("package.json"), b"{}").unwrap();
        let ten_days = std::time::SystemTime::now() - std::time::Duration::from_secs(10 * 86_400);
        std::fs::File::options()
            .write(true)
            .open(old.join("package.json"))
            .unwrap()
            .set_modified(ten_days)
            .unwrap();
        assert_eq!(idle_days(&old, None), Some(10));
        assert!(
            !paths.iter().any(|p| p.contains("docs/target")),
            "unmarked 'target' dir must not be a candidate"
        );
    }

    #[test]
    fn cancelled_discovery_returns_empty_plan() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("Projects/x/node_modules")).unwrap();
        std::fs::write(tmp.path().join("Projects/x/package.json"), b"{}").unwrap();
        let config_dir = tmp
            .path()
            .join(".config")
            .join(mole_core::brand::CONFIG_DIR);
        std::fs::create_dir_all(&config_dir).unwrap();
        std::fs::write(
            config_dir.join("purge_paths"),
            format!("{}/Projects\n", tmp.path().display()),
        )
        .unwrap();
        let cancel: CancelFlag = Arc::new(AtomicBool::new(true));
        let out = build_plan(&tmp.path().to_string_lossy(), &cancel, |_| {});
        assert!(out.plan.candidates.is_empty());
    }
}
